[package]
name = "metaphysics"
version = "0.1.0"
edition = "2024"
description = "Generic extendable first-order differential equation solver "
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
license = "GPL-3.0-or-later"

[features]
default = ["std"]
std = ["glam/std"]

[dependencies]
glam = { version = "0.27.0", default-features = false }
derive_more = { version = "2.0.1", features = ["from", "into"] }
